### ISSUE TITLE
FYPO:0006790 & FYPO:0006793 annotations don't appear

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-config#10]
Any idea why annotations to FYPO:0006790 or FYPO:0006793 don't show up on any of the PomBase web pages? At present all are from PMID:30475921, and other annotations from that paper show up on the publication page, and gene & ontology term pages. The term pages for FYPO:0006790 and FYPO:0006793 "know" there are annotations -- they offer the usual links to alleles and genes. But the annotation details don't appear.

**Comment by mah11** [comment]
I put 'em under cell phenotype (despite what the commit msg says :P )

**Comment by kimrutherford** [comment]
> I put 'em under cell phenotype (despite what the commit msg says :P )

Thanks.

Turns out that there was a bug in the display code as well.  Annotations that were directly to the high level terms in the configuration weren't displayed.  I assume we didn't spot the problem because there weren't that many annotations directly to the high level terms.

This is an example:
https://www.pombase.org/term/FYPO:0003427

The two annotations directly to "decreased queuosine level in tRNA" were not being shown.

Now fixed!
