### ISSUE TITLE
Modification config term availability

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#34]
I wanted to use GO:001097 in the "required for process" slot on a modification (it had "mitotic M phase" but this is a phase not a process.
However, most of what is available appear to be phases.

I forced with free text option
required_for_process(GO:001097)

**Comment by mah11** [comment]
Decide what you want to add to the options in this line (i.e. add one or more GO IDs to "GO:0022403|GO:0033554|GO:0072690"):

`MOD:00000	is_a	required_for	GO:0022403|GO:0033554|GO:0072690	required for process		0,1	user`

**Comment by mah11** [comment]
p.s. "GO:001097" is missing a digit

**Comment by ValWood** [comment]
actually this is a duplicate of
https://github.com/pombase/pombase-config/issues/35

**Comment by ValWood** [comment]
block all GO:0044848 biological phase form process extensions (is it possible to eliminate an entire branch? I forget?)

**Comment by mah11** [comment]
The modification extensions have been configured (by you or Antonia? I don't remember doing it myself) to allow "cellular response to" terms, cell cycle phase terms, and the "vegetative growth phase" term. In other words, phases have been deliberately *included* up to now.

Basically you're deciding to make a complete change in what can go in process extensions for modifications ... nothing wrong with that in principle, but well worth double-checking to make sure you really want to go ahead, and for which extension types.

In general, the extension configurations work mainly by specifying what to include; if you want to exclude a whole branch, simply don't include it. (The exception is that we can include all of branch except for a specified sub-branch, but that's not the issue here.)

There is no "occurs during" extension type for modification (or anything else); there's added, removed, present, and absent varieties of "during". That makes sense, because these annotations mean modification in the sense of the physical moiety attached to the substrate rather than the action of adding/removing/altering them. In onto-jargon, they're continuants, not occurrents.

I'm also still not entirely clear on which GO terms you want added/included for modification extensions.

Tangent: I don't think the slash causes any search problems. It's much more likely that if something isn't found, it's because the configuration doesn't cover it. I'm fairly sure that pasting IDs overrides the config restrictions (and the text-edit option definitely does).

**Comment by ValWood** [comment]
OK first we should check what has been used. I'm pretty sure I haven't used phases here because the prompt is
"
	•	"required for process"

The phases are used for the other varieties of during (added,removed etc0

It would not really make sense to have

happens during "G2 phase"
involved in "G2 phase" 

in the same way that it wouldn't make sense to   make a process annotation to "G2 phase"
so I think their inclusion is just a mistake. I always found it annoying that I could see the phase terms here.

**Comment by ValWood** [comment]
> I'm also still not entirely clear on which GO terms you want added/included for modification extensions.

I imagined all GO terms except the phase branch ....

**Comment by ValWood** [comment]
https://github.com/pombase/pombase-chado/issues/794
but I don't think we need to wait for the answer to remove these from the options

**Comment by mah11** [comment]
I was confused yesterday because the original summaries here and in #35 didn't make it clear that "required for process" should offer a different set of terms than the "during" extensions -- it does make sense for "during" to offer phases.

> I imagined all GO terms except the phase branch ....

OK, I *know* this one is rushed typing -- you don't really want GO CC terms in that config, right?

But would it make sense to include any MFs, e.g. the catalytic activity branch? (The prompt could change to "required for activity or process".)

For now I've put in all cellular processes and removed phases for "required for process", and left added/removed/present/absent during unchanged. If you want any MFs I'll add them; otherwise this can close.

**Comment by ValWood** [comment]
There are 2 extensions
required for activity
and
required for process
so only process - phases for "required for process"
