### ISSUE TITLE
extension prompts for histone modification phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#59]
For this annotation/term
<img width="1063" alt="Screenshot 2021-03-15 at 11 40 29" src="https://user-images.githubusercontent.com/7359272/111148389-7bd99880-8583-11eb-9666-902587d13d4e.png">

there are 2 components, the histone k9 methylation is reduced AT the mei4 heterochromatin island.

The protein modification is in the term name, so I didn't really need to capture it here.
However, it might be confusing that if I select  'gene or region' and add mei4, I can no longer specify the histone (although I can specify the residues).

It doesn't really matter here because histone is explicit. but I wondered if we should allow both. Or why allow residue, but not modified protein.
These might be a better example of this using a different term.
It's also reasonable to assume that we want the region here since the modified protein is in the label...

<img width="663" alt="Screenshot 2021-03-15 at 11 40 56" src="https://user-images.githubusercontent.com/7359272/111149062-500ae280-8584-11eb-979c-be3287fb7571.png">

**Comment by mah11** [comment]
> ... histone is explicit. but I wondered if we should allow both. Or why allow residue, but not modified protein.

I agree that it's redundant to prompt for information that's already in the term. We can eliminate some (maybe all) of the redundancy for the histone modification phenotypes by changing the normal/abnormal protein modification configuration to exclude the histone modification branch. I'll do that for "position of affected modification" and "assayed protein", because it'll help make the extension prompts saner for a bunch of terms.

> It's also reasonable to assume that we want the region here ...

It's always dangerous to assume much of anything ;)

No protein modification terms are directly configured to prompt for "gene or region" extensions. The histone modification terms inherit the "gene or region" prompt from the "chromatin modification" phenotype prompts (not from the protein modification side of their family), which in turn is because FYPO parallels the ancestry of "histone modification" in GO.

If that makes sense to you, we can leave that part of the FYPO configuration as is, although I'm a little worried that it'll be redundant for a lot of the terms in this area (e.g. for all the "histone modification at blah" terms, e.g. "at centromere outer repeat", putting a "region" extension is redundant). Let me know whether it's worth time & effort to refine these prompts further.

> However, it might be confusing that if I select 'gene or region' and add mei4, I can no longer specify the histone (although I can specify the residues).

Something odd is happening with what Canto allows and disallows for these ... I can get it to let me add more than one thing for "gene or region" if I enter a region first. Then more weirdness with "assayed protein", but since I'm planning to make that one go away, let's see how it behaves afte the config updates I just did percolate through, and if it's still weird I'll try to describe it and/or demo it.

**Comment by ValWood** [comment]
It sounds as though you have it sorted.

**Comment by mah11** [comment]
extensions make sense now, and behavior with "gene or region" is for a canto ticket
