### ISSUE TITLE
expression options, add "induced" ?

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#69]
Could we add a new expression option "induced"?
At the moment we can say when something is increased and decreased, but we don't know if there is a basal level already, or if it is 'newly induced'

For example moa1 is induced during " meiotic prophase I".
This term would be a 'descendant' of increased, but would allow us to be more specific going forwards.

Is this the correct tracker? I thought we added new 'terms' recently, but I can't find the ticket for this?

**Comment by kimrutherford** [comment]
Is this a Canto change?

**Comment by mah11** [comment]
These descriptors live in the local mini-ontology `pombase_gene_expression_ontology.obo` in pombe-embl svn. I guess it's a bit of a grey area where change requests go, but I've been putting them on the curation tracker with the label ["in-house ontology"](https://github.com/pombase/curation/issues?q=is%3Aissue+label%3A"in-house+ontology").

On to the content:
It doesn't make sense to me to say an RNA or protein level is "induced". You induce (or repress) a process. So we could add "transcription induced" and/or "translation induced", probably as part of a new branch in the ontology. But we would have to be very careful about using such terms, because they would only be applicable in cases where the experiment really looks at transcription or translation, not just at RNA or protein level (if you only know that a level goes up, you haven't distinguished between more production and less degradation).

At least based on dictionary definitions, I also don't think "induce" conveys anything about whether the basal level (above which the process is induced) is necessarily zero; it could just be lower than after induction. Illustration: the *GAL1* promoter in *S. cerevisiae* (the one Gal4p binds) -- glucose represses transcription from it, galactose activates it, and raffinose does neither so there's some expression but not the tons you get with galactose.

**Comment by ValWood** [comment]
yes, too complicated. Also I forgot I could add absent for phases when expression is not observed!
