### ISSUE TITLE
"active in"

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#7]
Am I being dim?

The molecular function "active in. " extension  gives biological processes.

What is it for?

**Comment by mah11** [comment]
Where are you seeing this, and what BP terms appear? The only config line with "active in" is this one:

    GO:0003674	is_a	occurs_in	GO:0110165	active in	a cell part where the activity is observed	0,1	user

GO:0110165 is "cellular anatomical entity"

**Comment by ValWood** [comment]
Hmm, that would have been useful information...will locate...

**Comment by ValWood** [comment]
https://curation.pombase.org/pombe/curs/c72c3efc43c47d0d

These extension types are available for ribonuclease III activity (GO:0004525):
PR:nnn ID for gene product form
has function during
qualifier
active in
involved in biological process
cleaves

**Comment by mah11** [comment]
The stuff in the screenshot looks sensible.

I tested in a different session, and BP terms do appear in the autocomplete for it. I can't see why from the config -- it looks OK -- so have to ask @kimrutherford : any idea what's going on?

**Comment by kimrutherford** [comment]
I've fix this bug.

At some point OWLTools started returning extra relations that we didn't need and Canto wasn't filtering those relations properly.  Some of the relations cross between ontologies and caused some process terms to appear in the auto-complete when only GO:0110165 (and descendants) should.

An example is: 
Golgi to plasma membrane CFTR protein transport
`results in transport to from or in` (RO:0002344)
cellular anatomical entity

This bug was probably causing a lot of bad auto-complete suggestions so it's good that you spotted it.
