### ISSUE TITLE
Display text for "anchors"

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#73]
Dispaly text for "anchors"

Currently use "anchors" for some and has_input" for some. https://www.pombase.org/term/GO:0008093 

"Recruits" would be better, and is already used for adaptors  (see fo reg spc7)

i.e. "pcp1 the core spindle component  that recruits gamma-tubulin complex

The only one where anchored works better is
 https://www.pombase.org/term/GO:0008093 
because this isn't describing the recruitment of a specific protein.

**Comment by mah11** [comment]
hmm, I tried to get everything consistent with what you requested [here](https://github.com/pombase/pombase-config/issues/29#issuecomment-665197395) ... something must have slipped through some cracks. I'll check soon.

**Comment by ValWood** [comment]
I probably didn't cover these thoroughly, I am suggesting these labels a bit _Ad hoc_.

Probably the GO  term names of 'anchors' here aren't quite right either. That is also a work in progress.... there isn't a clear community consensus to name the 'recruiting factors' as a class. Anchor activity is close but I don't like it.

**Comment by mah11** [comment]
I've left descendants of GO:0008093 as "anchors" for now. Everything else under GO:0030674 (protein-macromolecule adaptor activity) should have "recruits".

I also fixed a typo that may have accounted for some of the appearances of "has input" on the GO:0008093 page. See how it looks after these changes take effect, and reopen this (or a new ticket) if you want any more changes.

**Comment by ValWood** [comment]
can 
GO:0030674 | protein-macromolecule adaptor activity

itself have recruits? or does that interfere with one child having anchors (Ivaguely remember a work around for that)

**Comment by mah11** [comment]
Short answer: let's try it and see.

Longer answer: The website config file has a slew of entries for what to show when has_input is used in extensions on various GO terms. If you want to do the editing, go to this part of the website config file:

https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json#L3526

and add this:

      {
        "rel_name": "has_input",
        "if_descendant_of": "GO:0030674",
        "display_name": "recruits",
        "reciprocal_display": "recruited by"
      },

More explanation:
The "if_descendant_of" specifies which branch of GO gets the display text shown. I *think* it must work by applying the configured display text to extensions on the indicated term and its is_a descendants, and  defaulting to what's specified for a parent/ancestor otherwise. I'm inferring that that's the only way it can show "has input" for anything, because as far as I can tell there isn't an entry for has_input that doesn't specify an "if_descendant_of" ID.

If my understanding is accurate, we could also delete all of the entries that currently have `"display_name": "recruits"` because they would become redundant.


p.s. I've also just committed some adjustments to the Canto extension config to make it more consistent with what we're talking about here.
p.p.s. let me know if you'd prefer me to do the edits

**Comment by ValWood** [comment]
Could you do this one?  Maybe test your hypothesis  for 'recruits'?

I will try for the next one (my head is full this week)
