### ISSUE TITLE
DNA binding tf prompt (pho7)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#91]
DNA binding transcription activator activity, RNA polymerase II specific 
has a mixture of extensions
<img width="958" alt="Screenshot 2023-02-21 at 12 07 02" src="https://user-images.githubusercontent.com/7359272/220387453-c4ecc1e9-1480-43f4-8f8f-9acd94eb3fa9.png">

I think "activates the transcription of" is the best option here, but currently in Canto the default is "regulates" and the display label is "has regulation target"

I think I can override this by changing to has_iput in the text field (because that is what all of the others have). I am going to do this now and check tomorrow.

@kimrutherford Can we look at this one together to figure out how to fix the configs

**Comment by kimrutherford** [comment]
> I think I can override this by changing to has_iput in the text field (because that is what all of the others have).

Which text field?

**Comment by kimrutherford** [comment]
>  but currently in Canto the default is "regulates"

I don't understand that bit.   Canto doesn't have default extension relations?

**Comment by kimrutherford** [comment]
The "activates transcription of" extensions are `has_input` in Chado and Canto but I was bit confused by them.  I couldn't understand how they were made in Canto because there is no extension configuration for `has_input` that I can see for GO:0001228.  But then I worked out that we changed `has_regulation_target` to `has_input` in https://github.com/pombase/website/issues/1937

So I now understand why we have `has_input` extensions but there's no way to make any more.  Is that the problem that needs fixing?
