### ISSUE TITLE
user reported incorrect prompt

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-config#98]
Website config
<img width="951" alt="Screenshot 2023-09-11 at 17 30 20" src="https://github.com/pombase/pombase-config/assets/7359272/45521f7d-e48c-4e2b-868f-a2fe7fd26f07">

should be inhibits. I thought we fixed this but I can't find a ticket do it might have been another term.

**Comment by ValWood** [comment]
I think we fixed catalytic activity, in the config file we have

 {
            "rel_name": "has_input",
            "if_descendant_of": "GO:0004857",
            "display_name": "inhibits",
            "reciprocal_display": "inhibited by"
        },

on enzyme inhibitor activity GO:0004857
GTPase inhibitor activity (GO:0005095)
so I'm a bit baffled by this one.

@kimrutherford  can hyou help.

**Comment by kimrutherford** [comment]
For each extension, the web code looks through configuration and uses the first config that it finds which matches.

We had this early in the list which was used for GO:0004857 because GO:0030234 is a parent:

```json
  {
     "rel_name": "has_input",
     "if_descendant_of": "GO:0030234",
     "display_name": "activates",
     "reciprocal_display": "activated by"
  }
```

I've moved that further down so the display should be OK in the morning.

It's different in Canto because it displays all matching configuration.

**Comment by kimrutherford** [comment]
> I've moved that further down so the display should be OK in the morning.

Since [the load failed](https://github.com/pombase/pombase-chado/issues/1099#issuecomment-1714852562) the main site is on Sunday night's version.

But the dev site has last night's (slightly broken) update and the display is correct: http://dev.pombase.kmr.nz/term/GO:0004857
